name: First Workflow
on: workflow_dispatch # This will ensure that the pipeline is manually triggered 
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print Goodbye
        run: echo "Done - bye!"
